### ISSUE TITLE
关于单个模块消融实验的对比基线

### ISSUE THREAD

**Issue by jiayujerry** [liuhw01/AMP-Net#4]
作者您好，想请教您我在阅读文章时的一个疑问：

文章中您提到backbone是ResNet-34，但是单个模块消融实验的baseline却是ResNet-32。请问这里的ResNet-32是如何实现的？

期待您的回复，非常感谢！

**Comment by liuhw01** [comment]
感謝您指出我們的寫作錯誤，我們使用的backbone都是ResNet-34，文中的‘ResNet-34’被錯誤書寫為了‘ResNet-32’，我們將在後續進行修改。
十分感謝您對我們工作的支持！

**Comment by jiayujerry** [comment]
感谢您的超及时回复！
